/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface GasAttackerInterface extends Interface {
    getFunction(nameOrSignature: "MAX_ITERATIONS" | "gasAttack" | "unpredictableGas"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'MAX_ITERATIONS', values?: undefined): string;
encodeFunctionData(functionFragment: 'gasAttack', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'unpredictableGas', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'MAX_ITERATIONS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gasAttack', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpredictableGas', data: BytesLike): Result;
  }

  

  export interface GasAttacker extends BaseContract {
    
    connect(runner?: ContractRunner | null): GasAttacker;
    waitForDeployment(): Promise<this>;

    interface: GasAttackerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_ITERATIONS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    gasAttack: TypedContractMethod<
      [iterations: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unpredictableGas: TypedContractMethod<
      [seed: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_ITERATIONS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'gasAttack'): TypedContractMethod<
      [iterations: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpredictableGas'): TypedContractMethod<
      [seed: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }