/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface GasBurnerInterface extends Interface {
    getFunction(nameOrSignature: "accumulator" | "burnCompute" | "burnMixed" | "burnStorage" | "sink"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'accumulator', values?: undefined): string;
encodeFunctionData(functionFragment: 'burnCompute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'burnMixed', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'burnStorage', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sink', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'accumulator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnCompute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnMixed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sink', data: BytesLike): Result;
  }

  

  export interface GasBurner extends BaseContract {
    
    connect(runner?: ContractRunner | null): GasBurner;
    waitForDeployment(): Promise<this>;

    interface: GasBurnerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    accumulator: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    burnCompute: TypedContractMethod<
      [iterations: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    burnMixed: TypedContractMethod<
      [writes: BigNumberish, iterations: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    burnStorage: TypedContractMethod<
      [writes: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sink: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'accumulator'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'burnCompute'): TypedContractMethod<
      [iterations: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burnMixed'): TypedContractMethod<
      [writes: BigNumberish, iterations: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burnStorage'): TypedContractMethod<
      [writes: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sink'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }