/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface StateManipulatorInterface extends Interface {
    getFunction(nameOrSignature: "callCount" | "getState" | "manipulateState" | "state"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'callCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getState', values?: undefined): string;
encodeFunctionData(functionFragment: 'manipulateState', values?: undefined): string;
encodeFunctionData(functionFragment: 'state', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'callCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'manipulateState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'state', data: BytesLike): Result;
  }

  

  export interface StateManipulator extends BaseContract {
    
    connect(runner?: ContractRunner | null): StateManipulator;
    waitForDeployment(): Promise<this>;

    interface: StateManipulatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    callCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getState: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    manipulateState: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    state: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'callCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getState'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'manipulateState'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'state'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }