/**
 * Canonical env → Redis mapping for hybrid config: non-secrets in Valkey; secrets stay in process.env.
 * Tier0: connection, listen ports, filesystem paths, Node runtime — always read from env.
 */

import type { ConfigServiceId } from "./config-constants.js";

/** Keys that must never be written to or read from Redis (secrets). */
export const SECRET_ENV_KEYS = new Set<string>([
  "ALTO_UTILITY_PRIVATE_KEY",
  "ALTO_EXECUTOR_PRIVATE_KEYS",
  "PAYMASTER_CONTRACT_SIGNER_PRIVATE_KEY",
  "PAYMASTER_REFILL_OWNER_PRIVATE_KEY",
  "CONTRACT_DEPLOYER_PRIVATE_KEY",
  "DASHBOARD_ALTO_UTILITY_KEY",
  "DASHBOARD_ALTO_EXECUTOR_KEYS",
  "TOOLS_PRIVATE_KEY",
]);

/** Keys that stay in env only (bootstrap / process / paths). */
export const TIER0_ENV_KEYS = new Set<string>([
  "VALKEY_URL",
  "VALKEY_KEY_PREFIX",
  "REDIS_URL",
  "REDIS_KEY_PREFIX",
  "NODE_ENV",
  "PAYMASTER_API_PORT",
  "NEXT_RUNTIME",
  "CONTRACT_DEPLOYER_PAYMASTER_ADDRESS_FILE",
  "CONTRACT_DEPLOYER_GAS_BURNER_ADDRESS_FILE",
  "CONTRACT_DEPLOYER_CONTRACTS_ARTIFACTS_PATH",
]);

/** Non-secret env keys per service, stored in Redis hash `config:<service>` after bootstrap. */
export const REDIS_CONFIG_KEYS_BY_SERVICE: Record<ConfigServiceId, readonly string[]> = {
  "paymaster-api": [
    "PAYMASTER_API_RPC_URL",
    "PAYMASTER_API_BUNDLER_URL",
    "PAYMASTER_API_VALIDITY_SECONDS",
    "PAYMASTER_CONTRACT_VERIFICATION_GAS_LIMIT",
    "PAYMASTER_CONTRACT_POSTOP_GAS_LIMIT",
    "PAYMASTER_API_NORMAL_MAX_GAS_UNITS",
    "PAYMASTER_API_DEPLOY_MAX_GAS_UNITS",
    "PAYMASTER_API_MIN_POSTOP_FEE_USDC_E6",
    "PAYMASTER_API_ENTRYPOINT_ADDRESS",
    "PAYMASTER_API_SERVICE_FEE_BPS",
    "PAYMASTER_API_PRICING_AMPLIFIER_BPS",
    "PAYMASTER_API_FALLBACK_USDC_PER_GAS_UNIT_E6",
    "PAYMASTER_API_REFILL_MIN_NATIVE_WEI",
    "PAYMASTER_API_REFILL_TARGET_MULTIPLIER_ENTRYPOINT_BPS",
    "PAYMASTER_API_REFILL_TARGET_MULTIPLIER_PAYMASTER_NATIVE_BPS",
    "PAYMASTER_API_REFILL_TARGET_MULTIPLIER_UTILITY_BPS",
    "PAYMASTER_API_REFILL_TARGET_MULTIPLIER_EXECUTOR_BPS",
  ],
  dashboard: [
    "DASHBOARD_RPC_URL",
    "PAYMASTER_API_URL",
    "DASHBOARD_BUNDLER_URL",
    "DASHBOARD_ENTRYPOINT_ADDRESS",
    "DASHBOARD_TREASURY_ADDRESS",
    "DASHBOARD_USDC_ADDRESS",
    "DASHBOARD_USEROPS_BLOCK_RANGE",
    "DASHBOARD_POLL_INTERVAL_MS",
    "POLL_INTERVAL_MS",
    "DASHBOARD_REFILL_SWAP_USDC_E6",
    "REFILL_SWAP_USDC_E6",
    "DASHBOARD_WORKER_SWAP_USDC_E6",
    "WORKER_SWAP_USDC_E6",
    "DASHBOARD_MIN_ENTRYPOINT_DEPOSIT_WEI",
    "MIN_ENTRYPOINT_DEPOSIT_WEI",
    "DASHBOARD_CAP_ENTRYPOINT_BALANCE_WEI",
    "CAP_ENTRYPOINT_BALANCE_WEI",
    "DASHBOARD_MIN_PAYMASTER_NATIVE_WATCH_WEI",
    "MIN_PAYMASTER_NATIVE_WATCH_WEI",
    "DASHBOARD_MIN_WORKER_DEPOSIT_WEI",
    "MIN_WORKER_DEPOSIT_WEI",
    "DASHBOARD_CAP_PAYMASTER_NATIVE_WATCH_WEI",
    "CAP_PAYMASTER_NATIVE_WATCH_WEI",
    "DASHBOARD_CAP_WORKER_BALANCE_WEI",
    "CAP_WORKER_BALANCE_WEI",
    "PAYMASTER_CONTRACT_TREASURY_ADDRESS",
    "PAYMASTER_ADDRESS",
  ],
  bundler: [
    "ALTO_RPC_URL",
    "PAYMASTER_CONTRACT_ENTRYPOINT_ADDRESS",
    "ALTO_NETWORK_NAME",
    "ALTO_LOG_ENV",
    "ALTO_LOG_LEVEL",
    "ALTO_MIN_BALANCE",
    "ALTO_BLOCK_RANGE_LIMIT",
  ],
  "contract-deployer": [
    "ANVIL_RPC",
    "CONTRACT_DEPLOYER_SKIP_DEPLOYMENTS",
    "CONTRACT_DEPLOYER_DEPLOY_PROJECT4_PAYMASTER",
    "CONTRACT_DEPLOYER_DEPLOY_GAS_BURNER",
    "PAYMASTER_CONTRACT_USDC_ADDRESS",
    "PAYMASTER_CONTRACT_SIGNER_ADDRESS",
    "PAYMASTER_CONTRACT_ENTRYPOINT_ADDRESS",
  ],
  shared: [],
};

export function isSecretEnvKey(name: string): boolean {
  return SECRET_ENV_KEYS.has(name);
}

export function isTier0EnvKey(name: string): boolean {
  return TIER0_ENV_KEYS.has(name);
}

export function allRedisConfigKeys(): string[] {
  const out = new Set<string>();
  for (const keys of Object.values(REDIS_CONFIG_KEYS_BY_SERVICE)) {
    for (const k of keys) out.add(k);
  }
  return [...out];
}

/** Keys that may be absent in Redis after bootstrap (empty env). Runtime uses defaults where applicable. */
export const OPTIONAL_REDIS_CONFIG_KEYS = new Set<string>([
  "SHARED_PRICING_ARCHIVE_SWAP_THRESHOLD",
  "DASHBOARD_TREASURY_ADDRESS",
  "PAYMASTER_ADDRESS",
  "PAYMASTER_API_PRICING_AMPLIFIER_BPS",
  "PAYMASTER_API_FALLBACK_USDC_PER_GAS_UNIT_E6",
  "PAYMASTER_API_NORMAL_MAX_GAS_UNITS",
  "PAYMASTER_API_DEPLOY_MAX_GAS_UNITS",
  "PAYMASTER_API_REFILL_MIN_NATIVE_WEI",
  "PAYMASTER_API_REFILL_TARGET_MULTIPLIER_ENTRYPOINT_BPS",
  "PAYMASTER_API_REFILL_TARGET_MULTIPLIER_PAYMASTER_NATIVE_BPS",
  "PAYMASTER_API_REFILL_TARGET_MULTIPLIER_UTILITY_BPS",
  "PAYMASTER_API_REFILL_TARGET_MULTIPLIER_EXECUTOR_BPS",
]);
