/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IEntryPointLikeInterface extends Interface {
    getFunction(nameOrSignature: "addStake" | "depositTo" | "withdrawStake" | "withdrawTo"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositTo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawStake', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawTo', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawTo', data: BytesLike): Result;
  }

  

  export interface IEntryPointLike extends BaseContract {
    
    connect(runner?: ContractRunner | null): IEntryPointLike;
    waitForDeployment(): Promise<this>;

    interface: IEntryPointLikeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addStake: TypedContractMethod<
      [unstakeDelaySec: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    depositTo: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'payable'
    >
    

    
    withdrawStake: TypedContractMethod<
      [withdrawAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawTo: TypedContractMethod<
      [withdrawAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addStake'): TypedContractMethod<
      [unstakeDelaySec: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'depositTo'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'withdrawStake'): TypedContractMethod<
      [withdrawAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawTo'): TypedContractMethod<
      [withdrawAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }