/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IEntryPointLike } from './IEntryPointLike.js';
export type { Project4Paymaster } from './Project4Paymaster.js';