/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
    export type PackedUserOperationStruct = {sender: AddressLike, nonce: BigNumberish, initCode: BytesLike, callData: BytesLike, accountGasLimits: BytesLike, preVerificationGas: BigNumberish, gasFees: BytesLike, paymasterAndData: BytesLike, signature: BytesLike}

    export type PackedUserOperationStructOutput = [sender: string, nonce: bigint, initCode: string, callData: string, accountGasLimits: string, preVerificationGas: bigint, gasFees: string, paymasterAndData: string, signature: string] & {sender: string, nonce: bigint, initCode: string, callData: string, accountGasLimits: string, preVerificationGas: bigint, gasFees: string, paymasterAndData: string, signature: string }
  

  export interface Project4PaymasterInterface extends Interface {
    getFunction(nameOrSignature: "CAP_PROFILE_DEPLOY" | "CAP_PROFILE_NORMAL" | "addStake" | "allowAllTargets" | "circuitBreakerGasThreshold" | "deposit" | "entryPoint" | "gasEstimationVarianceThreshold" | "getGlobalGasStats" | "getPricingCounters" | "getSenderGasStats" | "lastResetTimestamp" | "owner" | "paused" | "postOp" | "postOpOverheadGas" | "rateLimitMaxGasPerPeriod" | "rateLimitPeriodSeconds" | "recordGasPurchase" | "resetGasUsage" | "senderGasUsedThisPeriod" | "senderLastActivityTimestamp" | "senderOperationCount" | "senderTotalGasUsed" | "setAllowAllTargets" | "setCircuitBreakerThreshold" | "setGasEstimationVarianceThreshold" | "setPaused" | "setPostOpOverheadGas" | "setRateLimit" | "setTargetAllowed" | "setTreasury" | "setVerifier" | "targetAllowed" | "totalGasBoughtWei" | "totalGasUnitsProcessed" | "totalGasUsedThisPeriod" | "totalOperationsProcessed" | "totalUsdcSpentForGasE6" | "transferOwnership" | "treasury" | "usdc" | "validatePaymasterUserOp" | "verifier" | "withdrawStake" | "withdrawTo" | "withdrawUsdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AllowAllTargetsUpdated" | "CircuitBreakerTriggered" | "GasCharged" | "GasChargedWithReferral" | "GasPurchaseRecorded" | "GasUsageTracked" | "OwnershipTransferred" | "PausedUpdated" | "RateLimitUpdated" | "TargetAllowedUpdated" | "TreasuryUpdated" | "UsdcWithdrawn" | "VerifierUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'CAP_PROFILE_DEPLOY', values?: undefined): string;
encodeFunctionData(functionFragment: 'CAP_PROFILE_NORMAL', values?: undefined): string;
encodeFunctionData(functionFragment: 'addStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'allowAllTargets', values?: undefined): string;
encodeFunctionData(functionFragment: 'circuitBreakerGasThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'entryPoint', values?: undefined): string;
encodeFunctionData(functionFragment: 'gasEstimationVarianceThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'getGlobalGasStats', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPricingCounters', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSenderGasStats', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastResetTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'postOp', values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'postOpOverheadGas', values?: undefined): string;
encodeFunctionData(functionFragment: 'rateLimitMaxGasPerPeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'rateLimitPeriodSeconds', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordGasPurchase', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resetGasUsage', values?: undefined): string;
encodeFunctionData(functionFragment: 'senderGasUsedThisPeriod', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'senderLastActivityTimestamp', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'senderOperationCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'senderTotalGasUsed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setAllowAllTargets', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setCircuitBreakerThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setGasEstimationVarianceThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPaused', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setPostOpOverheadGas', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRateLimit', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTargetAllowed', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setVerifier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'targetAllowed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalGasBoughtWei', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalGasUnitsProcessed', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalGasUsedThisPeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalOperationsProcessed', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalUsdcSpentForGasE6', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'validatePaymasterUserOp', values: [PackedUserOperationStruct, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawStake', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawTo', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawUsdc', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'CAP_PROFILE_DEPLOY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CAP_PROFILE_NORMAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowAllTargets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'circuitBreakerGasThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'entryPoint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gasEstimationVarianceThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGlobalGasStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPricingCounters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSenderGasStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastResetTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postOp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postOpOverheadGas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rateLimitMaxGasPerPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rateLimitPeriodSeconds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordGasPurchase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetGasUsage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'senderGasUsedThisPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'senderLastActivityTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'senderOperationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'senderTotalGasUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAllowAllTargets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCircuitBreakerThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGasEstimationVarianceThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPaused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPostOpOverheadGas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRateLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTargetAllowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'targetAllowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalGasBoughtWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalGasUnitsProcessed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalGasUsedThisPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalOperationsProcessed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalUsdcSpentForGasE6', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatePaymasterUserOp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawUsdc', data: BytesLike): Result;
  }

  
    export namespace AllowAllTargetsUpdatedEvent {
      export type InputTuple = [allowAll: boolean];
      export type OutputTuple = [allowAll: boolean];
      export interface OutputObject {allowAll: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CircuitBreakerTriggeredEvent {
      export type InputTuple = [sender: AddressLike, gasUsed: BigNumberish, limit: BigNumberish];
      export type OutputTuple = [sender: string, gasUsed: bigint, limit: bigint];
      export interface OutputObject {sender: string, gasUsed: bigint, limit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GasChargedEvent {
      export type InputTuple = [sender: AddressLike, chargedUsdcE6: BigNumberish, baseChargeUsdcE6: BigNumberish, treasury: AddressLike, gasUnits: BigNumberish, actualGasCost: BigNumberish, actualUserOpFeePerGas: BigNumberish];
      export type OutputTuple = [sender: string, chargedUsdcE6: bigint, baseChargeUsdcE6: bigint, treasury: string, gasUnits: bigint, actualGasCost: bigint, actualUserOpFeePerGas: bigint];
      export interface OutputObject {sender: string, chargedUsdcE6: bigint, baseChargeUsdcE6: bigint, treasury: string, gasUnits: bigint, actualGasCost: bigint, actualUserOpFeePerGas: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GasChargedWithReferralEvent {
      export type InputTuple = [sender: AddressLike, baseChargeUsdcE6: BigNumberish, referralChargeUsdcE6: BigNumberish, totalChargeUsdcE6: BigNumberish, referralAddress: AddressLike, referralBps: BigNumberish, gasUnits: BigNumberish, actualGasCost: BigNumberish, actualUserOpFeePerGas: BigNumberish];
      export type OutputTuple = [sender: string, baseChargeUsdcE6: bigint, referralChargeUsdcE6: bigint, totalChargeUsdcE6: bigint, referralAddress: string, referralBps: bigint, gasUnits: bigint, actualGasCost: bigint, actualUserOpFeePerGas: bigint];
      export interface OutputObject {sender: string, baseChargeUsdcE6: bigint, referralChargeUsdcE6: bigint, totalChargeUsdcE6: bigint, referralAddress: string, referralBps: bigint, gasUnits: bigint, actualGasCost: bigint, actualUserOpFeePerGas: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GasPurchaseRecordedEvent {
      export type InputTuple = [usdcE6: BigNumberish, nativeWei: BigNumberish];
      export type OutputTuple = [usdcE6: bigint, nativeWei: bigint];
      export interface OutputObject {usdcE6: bigint, nativeWei: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GasUsageTrackedEvent {
      export type InputTuple = [sender: AddressLike, periodGasUsed: BigNumberish, totalGasUsed: BigNumberish];
      export type OutputTuple = [sender: string, periodGasUsed: bigint, totalGasUsed: bigint];
      export interface OutputObject {sender: string, periodGasUsed: bigint, totalGasUsed: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedUpdatedEvent {
      export type InputTuple = [paused: boolean];
      export type OutputTuple = [paused: boolean];
      export interface OutputObject {paused: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RateLimitUpdatedEvent {
      export type InputTuple = [oldLimit: BigNumberish, newLimit: BigNumberish];
      export type OutputTuple = [oldLimit: bigint, newLimit: bigint];
      export interface OutputObject {oldLimit: bigint, newLimit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TargetAllowedUpdatedEvent {
      export type InputTuple = [target: AddressLike, allowed: boolean];
      export type OutputTuple = [target: string, allowed: boolean];
      export interface OutputObject {target: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryUpdatedEvent {
      export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
      export type OutputTuple = [oldTreasury: string, newTreasury: string];
      export interface OutputObject {oldTreasury: string, newTreasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsdcWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish, caller: AddressLike];
      export type OutputTuple = [to: string, amount: bigint, caller: string];
      export interface OutputObject {to: string, amount: bigint, caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VerifierUpdatedEvent {
      export type InputTuple = [oldVerifier: AddressLike, newVerifier: AddressLike];
      export type OutputTuple = [oldVerifier: string, newVerifier: string];
      export interface OutputObject {oldVerifier: string, newVerifier: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Project4Paymaster extends BaseContract {
    
    connect(runner?: ContractRunner | null): Project4Paymaster;
    waitForDeployment(): Promise<this>;

    interface: Project4PaymasterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CAP_PROFILE_DEPLOY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CAP_PROFILE_NORMAL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addStake: TypedContractMethod<
      [unstakeDelaySec: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    allowAllTargets: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    circuitBreakerGasThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    entryPoint: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    gasEstimationVarianceThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getGlobalGasStats: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {totalOps: bigint, periodGasUsed: bigint, lastReset: bigint }],
      'view'
    >
    

    
    getPricingCounters: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {gasUnitsProcessed: bigint, usdcSpentForGasE6: bigint, gasBoughtWei: bigint }],
      'view'
    >
    

    
    getSenderGasStats: TypedContractMethod<
      [sender: AddressLike, ],
      [[bigint, bigint, bigint] & {totalGas: bigint, operationCount: bigint, averageGas: bigint }],
      'view'
    >
    

    
    lastResetTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    postOp: TypedContractMethod<
      [mode: BigNumberish, context: BytesLike, actualGasCost: BigNumberish, actualUserOpFeePerGas: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    postOpOverheadGas: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rateLimitMaxGasPerPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rateLimitPeriodSeconds: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    recordGasPurchase: TypedContractMethod<
      [usdcE6: BigNumberish, nativeWei: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resetGasUsage: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    senderGasUsedThisPeriod: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    senderLastActivityTimestamp: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    senderOperationCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    senderTotalGasUsed: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    setAllowAllTargets: TypedContractMethod<
      [allowAll: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setCircuitBreakerThreshold: TypedContractMethod<
      [threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setGasEstimationVarianceThreshold: TypedContractMethod<
      [thresholdBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPaused: TypedContractMethod<
      [_paused: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setPostOpOverheadGas: TypedContractMethod<
      [newOverheadGas: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setRateLimit: TypedContractMethod<
      [periodSeconds: BigNumberish, maxGasPerPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTargetAllowed: TypedContractMethod<
      [target: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setVerifier: TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    targetAllowed: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    totalGasBoughtWei: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalGasUnitsProcessed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalGasUsedThisPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalOperationsProcessed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalUsdcSpentForGasE6: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    validatePaymasterUserOp: TypedContractMethod<
      [userOp: PackedUserOperationStruct, arg1: BytesLike, arg2: BigNumberish, ],
      [[string, bigint] & {context: string, validationData: bigint }],
      'nonpayable'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdrawStake: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawTo: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawUsdc: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CAP_PROFILE_DEPLOY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CAP_PROFILE_NORMAL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addStake'): TypedContractMethod<
      [unstakeDelaySec: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'allowAllTargets'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'circuitBreakerGasThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'entryPoint'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'gasEstimationVarianceThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getGlobalGasStats'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {totalOps: bigint, periodGasUsed: bigint, lastReset: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getPricingCounters'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {gasUnitsProcessed: bigint, usdcSpentForGasE6: bigint, gasBoughtWei: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getSenderGasStats'): TypedContractMethod<
      [sender: AddressLike, ],
      [[bigint, bigint, bigint] & {totalGas: bigint, operationCount: bigint, averageGas: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'lastResetTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'postOp'): TypedContractMethod<
      [mode: BigNumberish, context: BytesLike, actualGasCost: BigNumberish, actualUserOpFeePerGas: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'postOpOverheadGas'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rateLimitMaxGasPerPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rateLimitPeriodSeconds'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'recordGasPurchase'): TypedContractMethod<
      [usdcE6: BigNumberish, nativeWei: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resetGasUsage'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'senderGasUsedThisPeriod'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'senderLastActivityTimestamp'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'senderOperationCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'senderTotalGasUsed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setAllowAllTargets'): TypedContractMethod<
      [allowAll: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCircuitBreakerThreshold'): TypedContractMethod<
      [threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setGasEstimationVarianceThreshold'): TypedContractMethod<
      [thresholdBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPaused'): TypedContractMethod<
      [_paused: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPostOpOverheadGas'): TypedContractMethod<
      [newOverheadGas: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRateLimit'): TypedContractMethod<
      [periodSeconds: BigNumberish, maxGasPerPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTargetAllowed'): TypedContractMethod<
      [target: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVerifier'): TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'targetAllowed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalGasBoughtWei'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalGasUnitsProcessed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalGasUsedThisPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalOperationsProcessed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalUsdcSpentForGasE6'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'validatePaymasterUserOp'): TypedContractMethod<
      [userOp: PackedUserOperationStruct, arg1: BytesLike, arg2: BigNumberish, ],
      [[string, bigint] & {context: string, validationData: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawStake'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawTo'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawUsdc'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AllowAllTargetsUpdated'): TypedContractEvent<AllowAllTargetsUpdatedEvent.InputTuple, AllowAllTargetsUpdatedEvent.OutputTuple, AllowAllTargetsUpdatedEvent.OutputObject>;
getEvent(key: 'CircuitBreakerTriggered'): TypedContractEvent<CircuitBreakerTriggeredEvent.InputTuple, CircuitBreakerTriggeredEvent.OutputTuple, CircuitBreakerTriggeredEvent.OutputObject>;
getEvent(key: 'GasCharged'): TypedContractEvent<GasChargedEvent.InputTuple, GasChargedEvent.OutputTuple, GasChargedEvent.OutputObject>;
getEvent(key: 'GasChargedWithReferral'): TypedContractEvent<GasChargedWithReferralEvent.InputTuple, GasChargedWithReferralEvent.OutputTuple, GasChargedWithReferralEvent.OutputObject>;
getEvent(key: 'GasPurchaseRecorded'): TypedContractEvent<GasPurchaseRecordedEvent.InputTuple, GasPurchaseRecordedEvent.OutputTuple, GasPurchaseRecordedEvent.OutputObject>;
getEvent(key: 'GasUsageTracked'): TypedContractEvent<GasUsageTrackedEvent.InputTuple, GasUsageTrackedEvent.OutputTuple, GasUsageTrackedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PausedUpdated'): TypedContractEvent<PausedUpdatedEvent.InputTuple, PausedUpdatedEvent.OutputTuple, PausedUpdatedEvent.OutputObject>;
getEvent(key: 'RateLimitUpdated'): TypedContractEvent<RateLimitUpdatedEvent.InputTuple, RateLimitUpdatedEvent.OutputTuple, RateLimitUpdatedEvent.OutputObject>;
getEvent(key: 'TargetAllowedUpdated'): TypedContractEvent<TargetAllowedUpdatedEvent.InputTuple, TargetAllowedUpdatedEvent.OutputTuple, TargetAllowedUpdatedEvent.OutputObject>;
getEvent(key: 'TreasuryUpdated'): TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
getEvent(key: 'UsdcWithdrawn'): TypedContractEvent<UsdcWithdrawnEvent.InputTuple, UsdcWithdrawnEvent.OutputTuple, UsdcWithdrawnEvent.OutputObject>;
getEvent(key: 'VerifierUpdated'): TypedContractEvent<VerifierUpdatedEvent.InputTuple, VerifierUpdatedEvent.OutputTuple, VerifierUpdatedEvent.OutputObject>;

    filters: {
      
      'AllowAllTargetsUpdated(bool)': TypedContractEvent<AllowAllTargetsUpdatedEvent.InputTuple, AllowAllTargetsUpdatedEvent.OutputTuple, AllowAllTargetsUpdatedEvent.OutputObject>;
      AllowAllTargetsUpdated: TypedContractEvent<AllowAllTargetsUpdatedEvent.InputTuple, AllowAllTargetsUpdatedEvent.OutputTuple, AllowAllTargetsUpdatedEvent.OutputObject>;
    

      'CircuitBreakerTriggered(address,uint256,uint256)': TypedContractEvent<CircuitBreakerTriggeredEvent.InputTuple, CircuitBreakerTriggeredEvent.OutputTuple, CircuitBreakerTriggeredEvent.OutputObject>;
      CircuitBreakerTriggered: TypedContractEvent<CircuitBreakerTriggeredEvent.InputTuple, CircuitBreakerTriggeredEvent.OutputTuple, CircuitBreakerTriggeredEvent.OutputObject>;
    

      'GasCharged(address,uint256,uint256,address,uint256,uint256,uint256)': TypedContractEvent<GasChargedEvent.InputTuple, GasChargedEvent.OutputTuple, GasChargedEvent.OutputObject>;
      GasCharged: TypedContractEvent<GasChargedEvent.InputTuple, GasChargedEvent.OutputTuple, GasChargedEvent.OutputObject>;
    

      'GasChargedWithReferral(address,uint256,uint256,uint256,address,uint256,uint256,uint256,uint256)': TypedContractEvent<GasChargedWithReferralEvent.InputTuple, GasChargedWithReferralEvent.OutputTuple, GasChargedWithReferralEvent.OutputObject>;
      GasChargedWithReferral: TypedContractEvent<GasChargedWithReferralEvent.InputTuple, GasChargedWithReferralEvent.OutputTuple, GasChargedWithReferralEvent.OutputObject>;
    

      'GasPurchaseRecorded(uint256,uint256)': TypedContractEvent<GasPurchaseRecordedEvent.InputTuple, GasPurchaseRecordedEvent.OutputTuple, GasPurchaseRecordedEvent.OutputObject>;
      GasPurchaseRecorded: TypedContractEvent<GasPurchaseRecordedEvent.InputTuple, GasPurchaseRecordedEvent.OutputTuple, GasPurchaseRecordedEvent.OutputObject>;
    

      'GasUsageTracked(address,uint256,uint256)': TypedContractEvent<GasUsageTrackedEvent.InputTuple, GasUsageTrackedEvent.OutputTuple, GasUsageTrackedEvent.OutputObject>;
      GasUsageTracked: TypedContractEvent<GasUsageTrackedEvent.InputTuple, GasUsageTrackedEvent.OutputTuple, GasUsageTrackedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PausedUpdated(bool)': TypedContractEvent<PausedUpdatedEvent.InputTuple, PausedUpdatedEvent.OutputTuple, PausedUpdatedEvent.OutputObject>;
      PausedUpdated: TypedContractEvent<PausedUpdatedEvent.InputTuple, PausedUpdatedEvent.OutputTuple, PausedUpdatedEvent.OutputObject>;
    

      'RateLimitUpdated(uint256,uint256)': TypedContractEvent<RateLimitUpdatedEvent.InputTuple, RateLimitUpdatedEvent.OutputTuple, RateLimitUpdatedEvent.OutputObject>;
      RateLimitUpdated: TypedContractEvent<RateLimitUpdatedEvent.InputTuple, RateLimitUpdatedEvent.OutputTuple, RateLimitUpdatedEvent.OutputObject>;
    

      'TargetAllowedUpdated(address,bool)': TypedContractEvent<TargetAllowedUpdatedEvent.InputTuple, TargetAllowedUpdatedEvent.OutputTuple, TargetAllowedUpdatedEvent.OutputObject>;
      TargetAllowedUpdated: TypedContractEvent<TargetAllowedUpdatedEvent.InputTuple, TargetAllowedUpdatedEvent.OutputTuple, TargetAllowedUpdatedEvent.OutputObject>;
    

      'TreasuryUpdated(address,address)': TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
      TreasuryUpdated: TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
    

      'UsdcWithdrawn(address,uint256,address)': TypedContractEvent<UsdcWithdrawnEvent.InputTuple, UsdcWithdrawnEvent.OutputTuple, UsdcWithdrawnEvent.OutputObject>;
      UsdcWithdrawn: TypedContractEvent<UsdcWithdrawnEvent.InputTuple, UsdcWithdrawnEvent.OutputTuple, UsdcWithdrawnEvent.OutputObject>;
    

      'VerifierUpdated(address,address)': TypedContractEvent<VerifierUpdatedEvent.InputTuple, VerifierUpdatedEvent.OutputTuple, VerifierUpdatedEvent.OutputObject>;
      VerifierUpdated: TypedContractEvent<VerifierUpdatedEvent.InputTuple, VerifierUpdatedEvent.OutputTuple, VerifierUpdatedEvent.OutputObject>;
    
    };
  }