/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { ExpensiveContract, ExpensiveContractInterface } from "../ExpensiveContract.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "data",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "iterations",
        "type": "uint256"
      }
    ],
    "name": "expensiveOperation",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60808060405234601557610187908161001a8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c80635bfd87131461006a5763f0ba84401461002f575f80fd5b34610066576020366003190112610066576004355f5481101561006657610057602091610127565b90549060031b1c604051908152f35b5f80fd5b34610066576020366003190112610066576004355f5b81811061008957005b5f5468010000000000000000811015610113578060016100ab92015f55610127565b81549060031b9083821b915f19901b191617905560015f905b606482106100d6575050600101610080565b8060011b90808204600214901517156100ff57600181018091116100ff576001909101906100c4565b634e487b7160e01b5f52601160045260245ffd5b634e487b7160e01b5f52604160045260245ffd5b5f5481101561013d575f805260205f2001905f90565b634e487b7160e01b5f52603260045260245ffdfea2646970667358221220eaffae3231023d28c02b08dc423b48d181e371b52f773fac4916bc5c994b2afa64736f6c634300081c0033";

  
      type ExpensiveContractConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ExpensiveContractConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class ExpensiveContract__factory extends ContractFactory {
    
      constructor(...args: ExpensiveContractConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<ExpensiveContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): ExpensiveContract__factory {
      return super.connect(runner) as ExpensiveContract__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ExpensiveContractInterface {
      return new Interface(_abi) as ExpensiveContractInterface;
    }
    
    override attach(address: string | Addressable): ExpensiveContract {
      return super.attach(address) as ExpensiveContract;
    }
  static connect(address: string, runner?: ContractRunner | null): ExpensiveContract {
      return new Contract(address, _abi, runner) as unknown as ExpensiveContract;
    }
  }

  
  