/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { GasAttacker, GasAttackerInterface } from "../GasAttacker.js";

  const _abi = [
  {
    "inputs": [],
    "name": "MAX_ITERATIONS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "iterations",
        "type": "uint256"
      }
    ],
    "name": "gasAttack",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "seed",
        "type": "uint256"
      }
    ],
    "name": "unpredictableGas",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346015576101b8908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081631d92c26d14610168575080633a9143df146100f7576390ae63501461003d575f80fd5b346100f35760203660031901126100f35760043561271081116100b8575f5b81811061006557005b5f60015b600a8306821061007d57505060010161005c565b808002908082048114901517156100a457600181018091116100a457600190910190610069565b634e487b7160e01b5f52601160045260245ffd5b60405162461bcd60e51b8152602060048201526013602482015272546f6f206d616e7920697465726174696f6e7360681b6044820152606490fd5b5f80fd5b346100f35760203660031901126100f35760405160208101428152600435604083015260408252606082019180831067ffffffffffffffff841117610154576103e892604052519020065f5b81811061014c57005b600101610143565b634e487b7160e01b5f52604160045260245ffd5b346100f3575f3660031901126100f3578061271060209252f3fea26469706673582212201b7ea1c0e6e8e7cacbf6551f3aebb5d9e77cccef7ce0abb5b4a71412a10ba3dd64736f6c634300081c0033";

  
      type GasAttackerConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: GasAttackerConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class GasAttacker__factory extends ContractFactory {
    
      constructor(...args: GasAttackerConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<GasAttacker & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): GasAttacker__factory {
      return super.connect(runner) as GasAttacker__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): GasAttackerInterface {
      return new Interface(_abi) as GasAttackerInterface;
    }
    
    override attach(address: string | Addressable): GasAttacker {
      return super.attach(address) as GasAttacker;
    }
  static connect(address: string, runner?: ContractRunner | null): GasAttacker {
      return new Contract(address, _abi, runner) as unknown as GasAttacker;
    }
  }

  
  