/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { GasBurner, GasBurnerInterface } from "../GasBurner.js";

  const _abi = [
  {
    "inputs": [],
    "name": "accumulator",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "iterations",
        "type": "uint256"
      }
    ],
    "name": "burnCompute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "writes",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "iterations",
        "type": "uint256"
      }
    ],
    "name": "burnMixed",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "writes",
        "type": "uint256"
      }
    ],
    "name": "burnStorage",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "sink",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346015576101fd908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081630338115414610178575080631ae338691461014d578063490407ea146100fa5780637bee13d3146100735763c74e820e14610053575f80fd5b3461006f575f36600319011261006f5760205f54604051908152f35b5f80fd5b3461006f57604036600319011261006f575f600435816024355b8082106100cb5750505f5b8181106100a157005b808301908184116100b7576001915f5501610098565b634e487b7160e01b5f52601160045260245ffd5b909260019060405160208101918252856040820152604081526100ef606082610191565b51902093019061008d565b3461006f57602036600319011261006f575f806004355b80821061011e575f839055005b90916001906040516020810191825284604082015260408152610142606082610191565b519020920190610111565b3461006f57602036600319011261006f576004355f5b81811061016c57005b806001915f5501610163565b3461006f575f36600319011261006f576020905f548152f35b90601f8019910116810190811067ffffffffffffffff8211176101b357604052565b634e487b7160e01b5f52604160045260245ffdfea26469706673582212202dae2024d4e1af466e906b2cbaf9548e6a0252c95e09a06854a93ef3757a67f564736f6c634300081c0033";

  
      type GasBurnerConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: GasBurnerConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class GasBurner__factory extends ContractFactory {
    
      constructor(...args: GasBurnerConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<GasBurner & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): GasBurner__factory {
      return super.connect(runner) as GasBurner__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): GasBurnerInterface {
      return new Interface(_abi) as GasBurnerInterface;
    }
    
    override attach(address: string | Addressable): GasBurner {
      return super.attach(address) as GasBurner;
    }
  static connect(address: string, runner?: ContractRunner | null): GasBurner {
      return new Contract(address, _abi, runner) as unknown as GasBurner;
    }
  }

  
  