/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { StateManipulator, StateManipulatorInterface } from "../StateManipulator.js";

  const _abi = [
  {
    "inputs": [],
    "name": "callCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getState",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "manipulateState",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "state",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60808060405234601c575f80555f60015561012990816100218239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c9081631865c57d1460dc575080634b28f9a21460c15780638fb793ba1460615763c19d93fb146043575f80fd5b34605d575f366003190112605d5760205f54604051908152f35b5f80fd5b34605d575f366003190112605d576001545f198114609d5760019081018082551660b1575f548060011b9080820460021490151715609d575f55005b634e487b7160e01b5f52601160045260245ffd5b5f5460018101809111609d575f55005b34605d575f366003190112605d576020600154604051908152f35b34605d575f366003190112605d576020905f548152f3fea2646970667358221220828ebc8ae09e47f58ae310f279a98856ee8f3fcaf2a32c66a961c5ea0e340cfe64736f6c634300081c0033";

  
      type StateManipulatorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: StateManipulatorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class StateManipulator__factory extends ContractFactory {
    
      constructor(...args: StateManipulatorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<StateManipulator & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): StateManipulator__factory {
      return super.connect(runner) as StateManipulator__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): StateManipulatorInterface {
      return new Interface(_abi) as StateManipulatorInterface;
    }
    
    override attach(address: string | Addressable): StateManipulator {
      return super.attach(address) as StateManipulator;
    }
  static connect(address: string, runner?: ContractRunner | null): StateManipulator {
      return new Contract(address, _abi, runner) as unknown as StateManipulator;
    }
  }

  
  