/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockERC20, MockERC20Interface } from "../../lib/MockERC20.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "allowance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "spender",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "approve",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "transfer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "transferFrom",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60808060405234601557610388908161001a8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c8063095ea7b3146102b157806323b872dd1461019457806340c10f191461015757806370a0823114610120578063a9059cbb146100af5763dd62ed3e1461005b575f80fd5b346100ab5760403660031901126100ab576100746102f8565b61007c61030e565b6001600160a01b039182165f908152600160209081526040808320949093168252928352819020549051908152f35b5f80fd5b346100ab5760403660031901126100ab576100c86102f8565b60243590335f525f6020528160405f2054106100ab57335f525f60205260405f206100f4838254610324565b905560018060a01b03165f525f60205261011360405f20918254610345565b9055602060405160018152f35b346100ab5760203660031901126100ab576001600160a01b036101416102f8565b165f525f602052602060405f2054604051908152f35b346100ab5760403660031901126100ab576001600160a01b036101786102f8565b165f525f60205260405f206101906024358254610345565b9055005b346100ab5760603660031901126100ab576101ad6102f8565b6101b561030e565b6001600160a01b039091165f818152600160209081526040808320338452909152902054604435929190831161027357805f525f6020528260405f20541061023757805f52600160205260405f2060018060a01b0333165f5260205260405f20610220848254610324565b90555f525f60205260405f206100f4838254610324565b60405162461bcd60e51b8152602060048201526014602482015273696e73756666696369656e742062616c616e636560601b6044820152606490fd5b60405162461bcd60e51b8152602060048201526016602482015275696e73756666696369656e7420616c6c6f77616e636560501b6044820152606490fd5b346100ab5760403660031901126100ab576102ca6102f8565b335f52600160205260405f209060018060a01b03165f5260205260405f206024359055602060405160018152f35b600435906001600160a01b03821682036100ab57565b602435906001600160a01b03821682036100ab57565b9190820391821161033157565b634e487b7160e01b5f52601160045260245ffd5b919082018092116103315756fea2646970667358221220c6eacfd48a1380924fba1fb6792cbbbc08ff6afaaac59a4c5e11185d54b7e27e64736f6c634300081c0033";

  
      type MockERC20ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockERC20ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockERC20__factory extends ContractFactory {
    
      constructor(...args: MockERC20ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockERC20 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockERC20__factory {
      return super.connect(runner) as MockERC20__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockERC20Interface {
      return new Interface(_abi) as MockERC20Interface;
    }
    
    override attach(address: string | Addressable): MockERC20 {
      return super.attach(address) as MockERC20;
    }
  static connect(address: string, runner?: ContractRunner | null): MockERC20 {
      return new Contract(address, _abi, runner) as unknown as MockERC20;
    }
  }

  
  