/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IPaymasterInterface extends Interface {
    getFunction(nameOrSignature: "validatePaymasterUserOp"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'validatePaymasterUserOp', values: [BytesLike, BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'validatePaymasterUserOp', data: BytesLike): Result;
  }

  

  export interface IPaymaster extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPaymaster;
    waitForDeployment(): Promise<this>;

    interface: IPaymasterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    validatePaymasterUserOp: TypedContractMethod<
      [userOp: BytesLike, userOpHash: BytesLike, maxCost: BigNumberish, ],
      [[string, bigint] & {context: string, validationData: bigint }],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'validatePaymasterUserOp'): TypedContractMethod<
      [userOp: BytesLike, userOpHash: BytesLike, maxCost: BigNumberish, ],
      [[string, bigint] & {context: string, validationData: bigint }],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }