/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ReentrancyAttackerInterface extends Interface {
    getFunction(nameOrSignature: "attack" | "attacked" | "paymaster"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'attack', values?: undefined): string;
encodeFunctionData(functionFragment: 'attacked', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymaster', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'attack', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attacked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymaster', data: BytesLike): Result;
  }

  

  export interface ReentrancyAttacker extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReentrancyAttacker;
    waitForDeployment(): Promise<this>;

    interface: ReentrancyAttackerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attack: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    attacked: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    paymaster: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attack'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'attacked'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'paymaster'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }