// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Ownable$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Ownable";
  readonly sourceName: "contracts/lib/Ownable.sol";
  readonly abi: [{"inputs":[],"name":"NotOwner","type":"error"},{"inputs":[],"name":"ZeroAddress","type":"error"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/lib/Ownable.sol";
  readonly buildInfoId: "solc-0_8_28-73db1da7be481ff9f5c612283d0bdd5dd4916cf8";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Ownable"]: Ownable$Type;
    ["contracts/lib/Ownable.sol:Ownable"]: Ownable$Type;
  }
}