/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPaymaster, IPaymasterInterface } from "../../ReentrancyAttacker.sol/IPaymaster.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "userOp",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "userOpHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "maxCost",
        "type": "uint256"
      }
    ],
    "name": "validatePaymasterUserOp",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "context",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "validationData",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IPaymaster__factory {
    static readonly abi = _abi;
    static createInterface(): IPaymasterInterface {
      return new Interface(_abi) as IPaymasterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPaymaster {
      return new Contract(address, _abi, runner) as unknown as IPaymaster;
    }
  }
  