/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { ReentrancyAttacker, ReentrancyAttackerInterface } from "../../ReentrancyAttacker.sol/ReentrancyAttacker.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_paymaster",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "stateMutability": "payable",
    "type": "fallback"
  },
  {
    "inputs": [],
    "name": "attack",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "attacked",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "paymaster",
    "outputs": [
      {
        "internalType": "contract IPaymaster",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608034606e57601f61017f38819003918201601f19168301916001600160401b03831184841017607257808492602094604052833981010312606e57516001600160a01b03811690819003606e575f80546001600160a81b03191691909117905560405160f890816100878239f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe6080806040526004361015602f575b505f5460ff8160a01c1615601e57005b60ff60a01b1916600160a01b175f55005b5f3560e01c9081631105f9411460a35750806316e4cbf914607e57639e5faafc146058575f600e565b34607a575f366003190112607a575f805460ff60a01b1916600160a01b179055005b5f80fd5b34607a575f366003190112607a575f546040516001600160a01b039091168152602090f35b34607a575f366003190112607a5760209060ff5f5460a01c1615158152f3fea2646970667358221220f43f3abddf705571991b94551165ce5af7a50e6e6044b4f614c293249fef6e7f64736f6c634300081c0033";

  
      type ReentrancyAttackerConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ReentrancyAttackerConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class ReentrancyAttacker__factory extends ContractFactory {
    
      constructor(...args: ReentrancyAttackerConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_paymaster: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_paymaster, overrides || {});
    };
    override deploy(_paymaster: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_paymaster, overrides || {}) as Promise<ReentrancyAttacker & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): ReentrancyAttacker__factory {
      return super.connect(runner) as ReentrancyAttacker__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ReentrancyAttackerInterface {
      return new Interface(_abi) as ReentrancyAttackerInterface;
    }
    
    override attach(address: string | Addressable): ReentrancyAttacker {
      return super.attach(address) as ReentrancyAttacker;
    }
  static connect(address: string, runner?: ContractRunner | null): ReentrancyAttacker {
      return new Contract(address, _abi, runner) as unknown as ReentrancyAttacker;
    }
  }

  
  